### ISSUE TITLE
compatability with swagger

### ISSUE THREAD

**Issue by IefVandepitte** [KevinDockx/HttpCacheHeaders#35]
When i try to access documentation for my API created with swagger while HttpCacheHeaders is added in the HTTP request pipeline, the server returns a 500. When HttpCacheHeaders is disabled, it works fine.

[ContactManager-20170529.txt](https://github.com/KevinDockx/HttpCacheHeaders/files/1034558/ContactManager-20170529.txt)

**Comment by Ming-Sizung** [comment]
Hello @KevinDockx It seems that in the Http cache header middle-ware, you have disposed the underlying stream. It might happen in the `using` statement here (https://github.com/KevinDockx/HttpCacheHeaders/blob/master/src/Marvin.Cache.Headers/HttpCacheHeadersMiddleware.cs#L135) or here (https://github.com/KevinDockx/HttpCacheHeaders/blob/master/src/Marvin.Cache.Headers/HttpCacheHeadersMiddleware.cs#L147). Please have a look into this.

@IefVandepitte By moving the `app.UseSwagger()` before `app.UseHttpCacheHeaders()` resolve this issue for now. It is a temporary solution because the Swagger middle-ware will stop further processing and respond with the swagger file without letting the http cache header middle-ware add the headers.

**Comment by KevinDockx** [comment]
I changed the timing of when the middleware writes our its response headers - that should fix this :)
