### ISSUE TITLE
Getting unwanted cache value from browser's cache

### ISSUE THREAD

**Issue by hanslai** [KevinDockx/HttpCacheHeaders#78]
**Step to duplicate**  (please see action code below)

1. Create a empty asp.net core 2.1 Web API Project then add nuget Marvin.Cache.Headers
2. Run the web api project
3. enter uri `http://localhost/api/values` with any browser.  (tested on Chrome and Edge)

The browser will always return the same DateTime value.  Yet if comment out app.UseHttpCacheHeaders(); the browser will always return the updated current DateTime value.  Tried to set MaxAge =0, but does not help.

If clean up the browser's cache, it will get the updated DateTime value once, but then will always get the same cached value afterward.  

Actually, all we want just a eTag to handle concurrency, we do not want any cache at all.

We found out this problem when doing the following test.

1.  User A get image portrait.jpg  (image of a cat)
2.  User B get image portrait.jpg  (image of a cat)
3.  User A update image portrait.jpg  to image of a dog
4.  User B get image portrait.jpg, but the image is still a image of a cat.

I am not sure if this is a bug, or it is just the way it is.  Please advice.  Thank you.

here is the simple action
```
        [HttpGet]
        public ActionResult<string> Get()
        {
            return DateTime.Now.ToString();
        }
```

startup.cs
```
    public class Startup
    {
        public Startup(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IConfiguration Configuration { get; }

        // This method gets called by the runtime. Use this method to add services to the container.
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().SetCompatibilityVersion(CompatibilityVersion.Version_2_2);
            services.AddHttpCacheHeaders();
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                // The default HSTS value is 30 days. You may want to change this for production scenarios, see https://aka.ms/aspnetcore-hsts.
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseHttpCacheHeaders();
            app.UseMvc();
            
        }
    }
```

**Comment by KevinDockx** [comment]
Hi,

a browser like Chrome automatically sends over ETags etc for validation/expiration model checks if one was returned in the original response.  So, the first time you'll get back a 200 Ok, and for additional requests to the same endpoint you'll get back a 304 Not Modified.  The Last-Modified date won't change in the response, as the response wasn't modified.  So it makes sense that the date isn't updated unless the resource is updated.  

But... in this case, I see you're updating an image.  May I ask how that image is updated?  If the headers middleware (or an in-between cache/CDN) doesn't know about the fact that the resource has been updated, it will assume the previous version is still valid.  Invalidation automatically happens when a resource is updated via a PUT request, but if the image is simply overwritten out of process, the middleware doesn't know about this.  Updating it via a PUT request should fix this.  You can also always get the latest version of a resource by sending a GET request without any cache/etag-related headers.  

Making manual invalidation possible and separating out using the middleware for caching and/or concurrency are both features that are planned for an upcoming version.  

Hope this clarifies things.

**Comment by hanslai** [comment]
Hi Kevin:

Thanks for your response, the image update is done with a Post, since all the files upload are done with Post right now.

For getting the image, actually we are not use a GET, the image is just loaded to the web page with a HTML <img> Tag, so we cannot set any headers with it.

I will talk to my colleague about using a Put or Patch to do image update and see what happens.  Once I have more info I will post the update here and close this issue.  thanks.

**Comment by hanslai** [comment]
Hi Kevin:

We did some more testing.  Even we did a Put using Postman, but the browser still will not get the newly update Datetime.  Please see code below.

However, Postman will always get the updated Datetime.  I also notice that Postman will update the Last-Modified every time, I send a Get, even I did not do any Put.

so, the browser is still getting unwanted cache value, even there is a Put update.

```
namespace WebApplication8.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        private static DateTime _now = DateTime.Now;
        [HttpGet]
        public ActionResult<string> Get()
        {
            return _now.ToString();
        }

        [HttpPut]
        public ActionResult Put()
        {
            _now = DateTime.Now;
            return NoContent();
        }
    }
}
```

**Comment by KevinDockx** [comment]
I'm going to link this with #73 - solving that will allow manual invalidation at any time, which will also mitigate issues like this.

**Comment by hanslai** [comment]
That will be great.

**Comment by KevinDockx** [comment]
@hanslai , I just implemented preliminary support for this, see https://github.com/KevinDockx/HttpCacheHeaders/commit/9af38de31eac93f16fcf4a0116dc6f852986b758

This did introduce a breaking change for those who implemented their own ValidatorValueStore, so it'll be a 5.0 release.  Won't be released right away as I need to thoroughly test this, but you can already give it a try if you want by downloading the source & building it, or by getting the package from my MyGet feed: https://www.myget.org/feed/Packages/marvin

There's a new controller included in the sample application that contains examples on how this works.
